In [1]:
import numpy as np

2)Write a function to find moving average in an array over a window:

In [2]:
def moving_average_sequence(array,window_size):
    no_of_elements=len(array)-window_size+1
    array1=np.array(array)
    moving_average=[]
    for i in range(no_of_elements):
        moving_average.append(sum(array1[i:i+window_size])/window_size)
    return np.array(moving_average)
    

In [3]:
moving_average_sequence([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [4]:
moving_average_sequence([10,20,30,40,50,60,70,80,90,100], 4)

array([25., 35., 45., 55., 65., 75., 85.])

1)Write a function so that the columns of the output matrix are powers of the input vector.

In [5]:
def AlexandreTheophile_Vandermonde(input_vector,bool):
    vector=np.array(input_vector)
    increasing=bool
    output_matrix=np.mat(np.vander(np.array(vector),increasing =bool))
    return output_matrix


In [6]:
AlexandreTheophile_Vandermonde([1, 2, 3, 4],False)

matrix([[ 1,  1,  1,  1],
        [ 8,  4,  2,  1],
        [27,  9,  3,  1],
        [64, 16,  4,  1]])